spring:
    application:
        name: zuul

server:
    port: 8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/dev/
  instance:
      leaseRenewalIntervalInSeconds: 2